version: '3'
name: metabase-postgresql
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:v0.48.0
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    depends_on:
      - postgres

  postgres:
    container_name: postgresql
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_USER: metabase
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: metabase
    volumes:
      - ../db-data:/var/lib/postgresql/data
